"""
Email notifications via AWS SES.
DSAR letter templating.
"""
from __future__ import annotations
import logging

import boto3
from botocore.exceptions import BotoCoreError, ClientError
from jinja2 import Environment, BaseLoader

from app.core.config import get_settings

log = logging.getLogger(__name__)
settings = get_settings()

DSAR_TEMPLATE = """
Subject: Data Subject Access & Erasure Request — {{ full_name or "Data Subject" }}

To whom it may concern at {{ broker_name }},

I am writing to exercise my rights under {{ regulation }} to request the immediate
erasure and/or access to any personal data you hold relating to:

  Name:  {{ full_name or "(provided upon verification)" }}
  Email: {{ email or "(provided upon verification)" }}
  Phone: {{ phone or "(not provided)" }}

Under {{ regulation }}, you are required to confirm whether you process my personal
data, provide a copy of that data, and erase it upon request within the statutory
deadline.

Please confirm receipt of this request and provide your intended timeline.
If you fail to comply, I reserve the right to file a complaint with the relevant
supervisory authority and/or seek legal remedy.

Regards,
{{ full_name or "The Data Subject" }}

--- [Generated by Vindica | Scan ID: {{ scan_id }} | {{ timestamp }}Z] ---
"""

env = Environment(loader=BaseLoader())
dsar_tmpl = env.from_string(DSAR_TEMPLATE)


def resolve_broker_privacy_email(broker_name: str, broker_url: str) -> str | None:
    """Return only an explicitly verified broker contact; never guess an address."""
    from urllib.parse import urlparse

    contacts = {str(key).lower(): str(value).strip() for key, value in settings.BROKER_PRIVACY_EMAILS.items()}
    hostname = (urlparse(broker_url).hostname or '').lower()
    keys = [broker_name.lower(), hostname, hostname.removeprefix('www.')]
    return next((contacts[key] for key in keys if contacts.get(key)), None)


def send_dsar_email(
    to_email: str,
    broker_name: str,
    scan_id: str,
    query: dict,
    regulation: str = 'GDPR Art. 17 / CCPA § 1798.105',
) -> bool:
    from datetime import datetime, timezone
    body = dsar_tmpl.render(
        broker_name=broker_name,
        full_name=query.get('full_name'),
        email=query.get('email'),
        phone=query.get('phone'),
        regulation=regulation,
        scan_id=scan_id,
        timestamp=datetime.now(timezone.utc).isoformat(),
    )
    return _send(to_email, f'DSAR Request — {broker_name}', body)


def send_scan_complete(notify_email: str, scan_id: str, risk_score: float, breach_count: int) -> bool:
    subject = f'Vindica scan complete — {breach_count} exposure(s) found'
    body = (
        f'Your Vindica scan ({scan_id}) is complete.\n\n'
        f'Risk score: {risk_score:.0f}/100\n'
        f'Breach records found: {breach_count}\n\n'
        f'View your full report at: {settings.PUBLIC_APP_URL.rstrip("/")}/scan/{scan_id}\n'
    )
    return _send(notify_email, subject, body)


def _send(to: str, subject: str, body: str) -> bool:
    try:
        ses_kwargs = {'region_name': settings.AWS_REGION}
        if settings.AWS_ACCESS_KEY_ID and settings.AWS_SECRET_ACCESS_KEY:
            ses_kwargs.update(
                aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
            )
        ses = boto3.client('ses', **ses_kwargs)
        ses.send_email(
            Source=settings.SES_FROM_EMAIL,
            Destination={'ToAddresses': [to]},
            Message={
                'Subject': {'Data': subject},
                'Body': {'Text': {'Data': body}},
            },
        )
        log.info('Email sent to %s', to)
        return True
    except (BotoCoreError, ClientError) as e:
        log.error('SES send failed: %s', e)
        return False
