"""
ReportingAgent — writes H1-formatted reports and submits via API.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path

from agents.base import BaseAgent


class ReportingAgent(BaseAgent):
    name = "reporter"
    max_turns = 15

    def __init__(self, state, branch_manager=None, dry_run: bool = False):
        super().__init__(state, branch_manager)
        self.dry_run = dry_run

    def get_tools(self) -> list[dict]:
        return [
            {
                "name": "write_and_submit",
                "description": "Write a professional H1 report for a finding and submit it",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "finding_id":  {"type": "string"},
                        "title":       {"type": "string", "description": "H1 report title (max 100 chars)"},
                        "summary":     {"type": "string"},
                        "steps":       {"type": "string", "description": "Numbered reproduction steps"},
                        "impact":      {"type": "string"},
                        "poc":         {"type": "string", "description": "Proof of concept (request/response)"},
                        "remediation": {"type": "string"},
                        "severity":    {"type": "string", "enum": ["critical","high","medium","low","none"]},
                    },
                    "required": ["finding_id", "title", "summary", "steps", "impact", "severity"],
                },
            },
            {
                "name": "list_approved_findings",
                "description": "List all triage-approved findings pending submission",
                "input_schema": {"type": "object", "properties": {}},
            },
        ]

    def build_user_message(self) -> str:
        approved = self.state.approved_findings()
        if not approved:
            return "No approved findings to report. Output: done."
        lines = [f"{f.id}: [{f.severity}] {f.title} — {f.url}" for f in approved]
        return (
            f"Write and submit H1 reports for {len(approved)} approved findings "
            f"in program '{self.state.program_handle}':\n\n"
            + "\n".join(lines)
            + "\n\nFor each finding call write_and_submit with a complete, professional report."
            + ("\n\n[DRY RUN — do not actually submit]" if self.dry_run else "")
        )

    def tool_list_approved_findings(self) -> list:
        return [
            {"id": f.id, "severity": f.severity, "title": f.title,
             "url": f.url, "description": f.description[:500]}
            for f in self.state.approved_findings()
        ]

    def tool_write_and_submit(
        self,
        finding_id: str,
        title: str,
        summary: str,
        steps: str,
        impact: str,
        severity: str,
        poc: str = "",
        remediation: str = "",
    ) -> dict:
        report_md = f"""## Summary

{summary}

## Steps to Reproduce

{steps}

## Impact

{impact}

## Proof of Concept

{poc or "See description above."}

## Remediation

{remediation or "Apply the principle of least privilege and validate all user-controlled inputs."}

---
*Report generated by autonomous bounty agent — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}*
"""
        # Save draft
        reports_dir = Path(self.state.hunt_dir) / "reports"
        reports_dir.mkdir(exist_ok=True)
        slug = finding_id.lower().replace(" ", "-")
        draft_path = reports_dir / f"{slug}_report.md"
        draft_path.write_text(report_md)

        # Update finding with report path
        for f in self.state.findings:
            if f.id == finding_id:
                f.description = summary
                break
        self.state.save()

        # Submit
        if self.dry_run or not os.environ.get("H1_API_TOKEN"):
            result = {"report_id": "dry-run", "status": "dry_run"}
        else:
            try:
                import sys
                sys.path.insert(0, str(Path(__file__).parent.parent / "tools"))
                from h1_api import submit_report
                api_result = submit_report(
                    handle=self.state.program_handle,
                    title=title[:100],
                    vulnerability_information=report_md,
                    severity_rating=severity,
                    impact=impact[:500],
                )
                report_id = api_result.get("data", {}).get("id", "unknown")
                result = {"report_id": report_id, "status": "submitted",
                          "url": f"https://hackerone.com/reports/{report_id}"}

                # Save API response
                resp_path = reports_dir / f"{slug}_h1_response.json"
                resp_path.write_text(json.dumps(api_result, indent=2))

                # Update finding
                for f in self.state.findings:
                    if f.id == finding_id:
                        f.h1_report_id = report_id
                        break
                self.state.submissions.append({
                    "finding_id": finding_id,
                    "report_id":  report_id,
                    "title":      title,
                    "severity":   severity,
                    "submitted_at": datetime.now(timezone.utc).isoformat(),
                })
                self.state.save()

                # Git commit
                if self.branch_manager:
                    self.branch_manager.commit_report(
                        report_id, title, severity, self.state.hunt_dir
                    )
            except Exception as e:
                result = {"error": str(e)}

        return result
